#include "Player.h"
#include "ScriptMgr.h"
#include "SpellInfo.h"
#include "SpellMgr.h"
#include "AreaTriggerScript.h"
#include "ScriptedCreature.h"
#include "ScriptedGossip.h"
#include <string>

using namespace std;

enum class SPECS_SKILL_IDS
{
    //RUGO
    ASSASSINATION = 253,
    COMBAT = 38,
    SUBTETLY = 39,
    //HUNTER
    SURVIVAL = 51,
    BEAST_MASTERY = 50,
    MARKSMANSHIP =163,
    // SHAMAN
    ENHANCEMENT = 373,
    ELEMENTAL_COMBAT = 375,
    RESTORATION_SHAMAN =374,
    // PRIEST
    HOLY_PRIEST = 56,
    DISCIPLINE=613,
    SHADOW = 78,
    // PALADIN
    RETRIBUTION = 184,
    PROTECTION_PALADIN =267,
    HOLY_PALADIN = 594,
    // MAGE
    FROST =6,
    FIRE = 8,
    ARCANE=237,
    // WARLOCK
    DEMONOLOGY = 354,
    AFFLICTION =355,
    DESTRUCTION =593,
    // WARRIOR
    PROTECTION_WARRIOR = 257,
    FURY = 256,
    ARMS = 26,
    // DRUID
    RESTORATION_DRUID =573,
    BALANCE =574,
    FERAL_COMBAT = 134,

};

enum class PROFFESSION_SKILL_IDS
{
    BLACKSMITHING = 164,
    LEATHERWORKING = 165,
    ALCHEMY = 171,
    HERBALISM = 182,
    MINING = 186,
    TAILORING = 197,
    ENGINEERING = 202,
    ENCHANTING = 333,
    SKINNING = 393,
    JEWELCRAFTING = 755,
    INSCRIPTION = 773,
    FISHING = 356,
    COOKING = 185,
    FIRST_AID = 129,
};

enum class PROFFESSION_SPELL_IDS
{
    BLACKSMITHING = 2018,
    LEATHERWORKING = 2108,
    ALCHEMY = 2259,
    HERBALISM = 2366,
    MINING = 2575,
    TAILORING = 3908,
    ENGINEERING = 4036,
    ENCHANTING = 7411,
    SKINNING = 8613,
    INSCRIPTION = 45357,
    FISHING = 7620,
    COOKING = 2550,
    FIRST_AID = 3273,
    JEWELCRAFTING = 25229,
};

enum class SKILL_IDS
{
    SWORDS = 43,
    AXES = 44,
    BOWS = 45,
    GUNS = 46,
    MACES = 54,
    TWO_H_SWORDS = 55,
    DEFENSE = 95,
    STAVES = 136,
    TWO_H_MACES = 160,
    TWO_H_AXES = 172,
    DAGGERS = 173,
    THROWN = 176,
    CROSSBOWS = 226,
    WANDS = 228,
    POLEARMS = 229,
    SHIELD = 433,
    FIST_WEAPONS = 473,
    LOCKPICKING = 633,
    MAIL = 413,
    PLATE = 293,
    LEATHER = 414,
    CLOTH = 415,
    DUAL_WIELD = 118
};

enum class SKILL_SPELL_IDS : uint32_t
{
    SWORDS = 201,
    AXES = 196,
    BOWS = 264,
    GUNS = 266,
    MACES = 198,
    TWO_H_SWORDS = 202,
    DEFENSE = 204,
    STAVES = 227,
    TWO_H_MACES = 199,
    TWO_H_AXES = 197,
    DAGGERS = 1180,
    THROWN = 2567,
    CROSSBOWS = 5011,
    WANDS = 5009,
    POLEARMS = 200,
    SHIELD = 9116,
    FIST_WEAPONS = 15590,
    MAIL = 8737,
    PLATE = 750,
    CLOTH = 9078,
    LEATHER = 9077,
    LOCKPICKING = 1804,

    DUAL_WIELD = 674,
    LANGUAGE_COMMON = 668,
    LIBRAM = 27762,
    BLOCK = 107,
    IDOL = 27764,
    UNARMED = 203,
    THROW = 2764,
    PARRY = 3127,
    SHOOT = 5019,
    DODGE = 81,
};

vector<pair<PROFFESSION_SKILL_IDS, PROFFESSION_SPELL_IDS>> autoLearnProfessions = {
    {PROFFESSION_SKILL_IDS::BLACKSMITHING, PROFFESSION_SPELL_IDS::BLACKSMITHING},
    {PROFFESSION_SKILL_IDS::LEATHERWORKING, PROFFESSION_SPELL_IDS::LEATHERWORKING},
    {PROFFESSION_SKILL_IDS::ALCHEMY, PROFFESSION_SPELL_IDS::ALCHEMY},
    {PROFFESSION_SKILL_IDS::HERBALISM, PROFFESSION_SPELL_IDS::HERBALISM},
    {PROFFESSION_SKILL_IDS::MINING, PROFFESSION_SPELL_IDS::MINING},
    {PROFFESSION_SKILL_IDS::TAILORING, PROFFESSION_SPELL_IDS::TAILORING},
    {PROFFESSION_SKILL_IDS::ENGINEERING, PROFFESSION_SPELL_IDS::ENGINEERING},
    {PROFFESSION_SKILL_IDS::ENCHANTING, PROFFESSION_SPELL_IDS::ENCHANTING},
    {PROFFESSION_SKILL_IDS::SKINNING, PROFFESSION_SPELL_IDS::SKINNING},
    {PROFFESSION_SKILL_IDS::JEWELCRAFTING, PROFFESSION_SPELL_IDS::JEWELCRAFTING},
    {PROFFESSION_SKILL_IDS::INSCRIPTION, PROFFESSION_SPELL_IDS::INSCRIPTION},
    {PROFFESSION_SKILL_IDS::FISHING, PROFFESSION_SPELL_IDS::FISHING},
    {PROFFESSION_SKILL_IDS::COOKING, PROFFESSION_SPELL_IDS::COOKING},
    {PROFFESSION_SKILL_IDS::FIRST_AID, PROFFESSION_SPELL_IDS::FIRST_AID},
};

vector<pair<SKILL_IDS, SKILL_SPELL_IDS>> autoLearnSkills = {
    {SKILL_IDS::SWORDS, SKILL_SPELL_IDS::SWORDS},
    {SKILL_IDS::AXES, SKILL_SPELL_IDS::AXES},
    {SKILL_IDS::BOWS, SKILL_SPELL_IDS::BOWS},
    {SKILL_IDS::GUNS, SKILL_SPELL_IDS::GUNS},
    {SKILL_IDS::MACES, SKILL_SPELL_IDS::MACES},
    {SKILL_IDS::TWO_H_SWORDS, SKILL_SPELL_IDS::TWO_H_SWORDS},
    {SKILL_IDS::DEFENSE, SKILL_SPELL_IDS::DEFENSE},
    {SKILL_IDS::STAVES, SKILL_SPELL_IDS::STAVES},
    {SKILL_IDS::TWO_H_MACES, SKILL_SPELL_IDS::TWO_H_MACES},
    {SKILL_IDS::TWO_H_AXES, SKILL_SPELL_IDS::TWO_H_AXES},
    {SKILL_IDS::DAGGERS, SKILL_SPELL_IDS::DAGGERS},
    {SKILL_IDS::THROWN, SKILL_SPELL_IDS::THROWN},
    {SKILL_IDS::CROSSBOWS, SKILL_SPELL_IDS::CROSSBOWS},
    {SKILL_IDS::WANDS, SKILL_SPELL_IDS::WANDS},
    {SKILL_IDS::POLEARMS, SKILL_SPELL_IDS::POLEARMS},
    {SKILL_IDS::SHIELD, SKILL_SPELL_IDS::SHIELD},
    {SKILL_IDS::FIST_WEAPONS, SKILL_SPELL_IDS::FIST_WEAPONS},
    {SKILL_IDS::LOCKPICKING, SKILL_SPELL_IDS::LOCKPICKING},
    {SKILL_IDS::MAIL, SKILL_SPELL_IDS::MAIL},
    {SKILL_IDS::PLATE, SKILL_SPELL_IDS::PLATE},
    {SKILL_IDS::LEATHER, SKILL_SPELL_IDS::LEATHER},
    {SKILL_IDS::CLOTH, SKILL_SPELL_IDS::CLOTH},
    {SKILL_IDS::DUAL_WIELD, SKILL_SPELL_IDS::DUAL_WIELD}
};

vector<SPECS_SKILL_IDS> classSpecs = {
    //RUGO
    SPECS_SKILL_IDS::ASSASSINATION,
    SPECS_SKILL_IDS::COMBAT,
    SPECS_SKILL_IDS::SUBTETLY,
    //HUNTER
    SPECS_SKILL_IDS::SURVIVAL,
    SPECS_SKILL_IDS::BEAST_MASTERY,
    SPECS_SKILL_IDS::MARKSMANSHIP,
    //SHAMAN
    SPECS_SKILL_IDS::ENHANCEMENT,
    SPECS_SKILL_IDS::ELEMENTAL_COMBAT,
    SPECS_SKILL_IDS::RESTORATION_SHAMAN,
    //PRIEST
    SPECS_SKILL_IDS::HOLY_PRIEST,
    SPECS_SKILL_IDS::DISCIPLINE,
    SPECS_SKILL_IDS::SHADOW,
    //PALADIN
    SPECS_SKILL_IDS::RETRIBUTION,
    SPECS_SKILL_IDS::PROTECTION_PALADIN,
    SPECS_SKILL_IDS::HOLY_PALADIN,
    //MAGE
    SPECS_SKILL_IDS::FROST,
    SPECS_SKILL_IDS::FIRE,
    SPECS_SKILL_IDS::ARCANE,
    //WARLOCK
    SPECS_SKILL_IDS::DEMONOLOGY,
    SPECS_SKILL_IDS::AFFLICTION,
    SPECS_SKILL_IDS::DESTRUCTION,
    //WARRIOR
    SPECS_SKILL_IDS::PROTECTION_WARRIOR,
    SPECS_SKILL_IDS::FURY,
    SPECS_SKILL_IDS::ARMS,
    //DRUID
    SPECS_SKILL_IDS::RESTORATION_DRUID,
    SPECS_SKILL_IDS::BALANCE,
    SPECS_SKILL_IDS::FERAL_COMBAT,
};

class LearnClasslessDefaults : public PlayerScript
{
public:
    LearnClasslessDefaults() : PlayerScript("LearnClasslessDefaults") {
        
    }

       

    void OnPlayerFirstLogin (Player *player) override
    {
        
            for (const auto& skills : autoLearnSkills)
            {
                player->SetSkill(static_cast<uint16_t>(skills.first), 5, 1, 5);
                player->learnSpell(static_cast<uint32_t>(skills.second), false, false);
            }

            for (const auto& profession : autoLearnProfessions)
            {
                player->SetSkill(static_cast<uint16_t>(profession.first), 75, 1, 1);
                player->learnSpell(static_cast<uint32_t>(profession.second), false, false);
            }

            for (const auto& spec : classSpecs)
            {
                player->SetSkill(static_cast<uint16_t>(spec), 300, 1, 1);
            }
      


    }
};

void AddSC_LearnAllSpells()
{
    new LearnClasslessDefaults();
}
